# Generated by Django 5.0.6 on 2024-06-19 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
