# Generated by Django 5.0.6 on 2024-06-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_timestamp_move_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='n',
            new_name='board_size',
        ),
    ]
