# Generated by Django 5.0.6 on 2024-06-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_n_board_board_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_size',
            new_name='size',
        ),
    ]
