# Generated by Django 4.2.13 on 2024-06-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_board_size_board_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='turn',
            field=models.CharField(choices=[('player1', 'Host'), ('player2', 'Guest')], default='player1', max_length=7),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='winner',
            field=models.CharField(blank=True, choices=[('player1', 'Host'), ('player2', 'Guest')], max_length=7, null=True),
        ),
    ]
