# Generated by Django 4.2.13 on 2024-06-20 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_alter_gameroom_turn_alter_gameroom_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='online_users',
            field=models.ManyToManyField(blank=True, related_name='online_in_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
