# Generated by Django 4.2.13 on 2024-06-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_gameroom_turn_remove_gameroom_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='is_complete',
        ),
    ]
