# Generated by Django 4.2.13 on 2024-06-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_board_is_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Move',
        ),
    ]
