# Generated by Django 4.2.13 on 2024-06-29 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0009_delete_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victories', to=settings.AUTH_USER_MODEL),
        ),
    ]
