# Generated by Django 4.2.13 on 2024-06-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_board_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
